/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.BorderFactory;
import napakalaki.BadConsequence;
import napakalaki.NumericBadConsequence;
import napakalaki.DeathBadConsequence;
import napakalaki.SpecificBadConsequence;

/**
 *
 * @author Ludvins
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    BadConsequence bc;
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
        this.setBorder(BorderFactory.createTitledBorder("Pending Bad Consequence"));
    }
    
    public void setBadConsequence(BadConsequence b){
        bc = b;
        if (b instanceof NumericBadConsequence){
            jLabel3.setText(Integer.toString(((NumericBadConsequence) b).getnVisibleTreasures()));
            jLabel4.setText(Integer.toString(((NumericBadConsequence) b).getnHiddenTreasures()));
        }
        if (b instanceof SpecificBadConsequence){
            if ( ((SpecificBadConsequence) b).getSpecificVisibleTreasures().isEmpty() && ((SpecificBadConsequence) b).getSpecificHiddenTreasures().isEmpty() ){
                
                jLabel3.setText("");
                jLabel4.setText(""); 
                
            }else{
                
                jLabel3.setText( "<html>" + ((SpecificBadConsequence) b).getSpecificVisibleTreasures().toString()  + "</html>");
                jLabel4.setText( "<html>" + ((SpecificBadConsequence) b).getSpecificHiddenTreasures().toString()  + "</html>");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("Visible Treasures:");

        jLabel2.setText("Hidden Treasures:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
